meta:
  environment: root-env-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: root_env_leader_z1
    instances: 1
    networks:
      - name: root_env1
        static_ips: (( static_ips(0) ))
  - name: root_env_z1
    instances: 2
    networks:
      - name: root_env1
        static_ips: ~
    properties:
      root_env:
        leader_address: (( jobs.root_env_leader_z1.networks.root_env1.static_ips.[0] ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: root_env1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.20.0/30
    reserved:
    - 10.244.20.1
    static:
    - 10.244.20.2

  - cloud_properties:
      name: random
    range: 10.244.20.4/30
    reserved:
    - 10.244.20.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.8/30
    reserved:
    - 10.244.20.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.12/30
    reserved:
    - 10.244.20.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.16/30
    reserved:
    - 10.244.20.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.20.20/30
    reserved:
    - 10.244.20.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.24/30
    reserved:
    - 10.244.20.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.28/30
    reserved:
    - 10.244.20.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.32/30
    reserved:
    - 10.244.20.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.36/30
    reserved:
    - 10.244.20.37
    static: []
