meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: root_env_z1
    templates:
    - name: root-env
      release: root-env
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      root_env:
        env_tarball: (( merge ))

networks: (( merge ))

properties: {}
